#!/bin/zsh

cd ~/projects

repos=('calvinhobbes' 'compare-versions' 'daily-glry' 'dilbert' 'glry-search-api' 'glry-search' 'glry' 'kuranz' 'redux-promise-middleware-actions' 'regex-crossword-api' 'regex-lib' 'regex-mobile' 'regex-solver')

for repo in $repos; do
  git clone --quiet https://github.com/omichelsen/$repo.git
  cd $repo
  git fetch --prune
  git pull
  if [[ -e yarn.lock ]]; then
    yarn --silent install
  fi
  if [[ -e package-lock.json ]]; then
    npm --silent install
  fi
  cd ..
done

git clone --quiet https://olemichelsen@bitbucket.org/olemichelsen/regex-crossword.git
git clone --quiet https://olemichelsen@bitbucket.org/olemichelsen/sendpoll.git
