#!/bin/zsh

exists() { command -v "$1" >/dev/null 2>&1 }

## INSTALL

# homebrew
if ! exists brew; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# less syntax highlight
if ! exists source-highlight; then
	brew install source-highlight
fi

# VSC
if ! exists code; then
  brew cask install visual-studio-code
  cat Code/extensions.bak | xargs -n 1 code --install-extension
fi

## SETTINGS

# Close System Preferences to prevent overriding settings
osascript -e 'tell application "System Preferences" to quit'

# System Preferences > General > Close windows when quitting an app
defaults write -globalDomain NSQuitAlwaysKeepsWindows 1

# System Preferences > Dock > Automatically hide and show the Dock:
defaults write com.apple.dock autohide -bool true
