#!/bin/zsh

# zsh
echo "creating symlinks for zsh (bash)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ln -sf ~/config/.zprofile ~/.zprofile
ln -sf ~/config/.zshrc ~/.zshrc

# git
echo "creating symlinks for git"
ln -sf ~/config/.gitconfig ~/.gitconfig
ln -sf ~/config/.gitignore_global ~/.gitignore_global

# vsc
if [[ "$OSTYPE" == "darwin"* ]]; then
	echo "creating symlinks for VSC Mac"
	ln -sf ~/config/Code/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json
	ln -sf ~/config/Code/settings.json ~/Library/Application\ Support/Code/User/settings.json
	ln -sf ~/config/Code/snippets ~/Library/Application\ Support/Code/User/
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo "creating symlinks for VSC Linux"
	ln -sf ~/config/Code/keybindings.json ~/.config/Code/User/keybindings.json
	ln -sf ~/config/Code/settings.json ~/.config/Code/User/settings.json
	ln -sf ~/config/Code/snippets ~/.config/Code/User/
fi

# homebrew
if [[ "$OSTYPE" == "darwin"* ]]; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

# > ~/.ssh/config
# Host *
# 	AddKeysToAgent yes
# 	UseKeychain yes
# 	IdentityFile ~/.ssh/id_rsa
